# Site settings
title: ĐẤT THỔ CƯ CỦ CHI CHÍNH CHỦ 3000 M2
email: dangphamza@gmail.com
điện thoại: 0348139669
description: > # this means to ignore newlines until "baseurl:"
  Đất thổ cư củ chi chính chủ 500 m2, vị trí đẹp mặt tiền Nguyễn Thị Rành, cách quốc lộ 22, cầu vượt củ chi 2 Km
baseurl: "" # the subpath of your site, e.g. /blog/
url: "dangphamvst.github.io" # the base hostname & protocol for your site
twitter_username: dangphampv
github_username:  dangphampv

# Build settings
markdown: dangpham

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
